spring:
  lifecycle.timeout-per-shutdown-phase: ${SHUTDOWN_TIMEOUT:30s}
  datasource:
    url: jdbc:mysql://${DATABASE_SERVER_NAME}:3306/k8s_java
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_USER_PASSWORD}

  jpa.hibernate.ddl-auto: none
