spring:
  datasource:
    url: jdbc:mysql://${DATABASE_SERVER_NAME:localhost}:3306/k8s_java
    username: ${DATABASE_USER_NAME:java}
    password: ${DATABASE_USER_PASSWORD:1234}
  # dont do this in production!!
  jpa:
    hibernate:
      ddl-auto: create
