spring:
  lifecycle.timeout-per-shutdown-phase: ${SHUTDOWN_TIMEOUT:30s}
  profiles.active: ${SPRING_PROFILE:dev}

info.app:
    name: java-kubernetes
    description: Demo Kubernetes for Java Developers

management:
  endpoint.metrics.enabled: true
  endpoints.web.exposure.include: info,health,prometheus,metrics
  health.probes.enabled: true

server:
  shutdown: graceful
  servlet.context-path: /app
