apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
  namespace: dev-to
data:
  DATABASE_SERVER_NAME: "mysql"
  DATABASE_USER_NAME: "myapp"
  DATABASE_USER_PASSWORD: "myapp_pwd"
  # The following command will listen to a port 5005 for debug the application
  JAVA_OPTS: "--enable-preview -agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n -XX:MaxRAMPercentage=80"
  # The following command set the JVM maximum memory to 80%
  # JAVA_OPTS: "--enable-preview -XX:MaxRAMPercentage=80"
